/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as YourPlanImport } from './routes/YourPlan'
import { Route as IndexImport } from './routes/index'

// Create/Update Routes

const YourPlanRoute = YourPlanImport.update({
  id: '/YourPlan',
  path: '/YourPlan',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/YourPlan': {
      id: '/YourPlan'
      path: '/YourPlan'
      fullPath: '/YourPlan'
      preLoaderRoute: typeof YourPlanImport
      parentRoute: typeof rootRoute
    }
  }
}

// Create and export the route tree

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/YourPlan': typeof YourPlanRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/YourPlan': typeof YourPlanRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/YourPlan': typeof YourPlanRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/YourPlan'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/YourPlan'
  id: '__root__' | '/' | '/YourPlan'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  YourPlanRoute: typeof YourPlanRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  YourPlanRoute: YourPlanRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/YourPlan"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/YourPlan": {
      "filePath": "YourPlan.tsx"
    }
  }
}
ROUTE_MANIFEST_END */
